# 1 Wite a program to compute 5/0 or try except 

In [1]:
(a,b) = (6,0)
try:
    g = a/b
except ZeroDivisionError:
    print ("This is a DIVIDED BY ZERO error")

This is a DIVIDED BY ZERO error


# 2 

In [14]:
subjects=["Americans","Indian"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
for i in subjects:
    for j in verbs:
        for k in objects:
            print(i,end=' ')
            print(j,end=' ')
            print(k,end=' ')
            print("\n")

Americans play Baseball 

Americans play Cricket 

Americans watch Baseball 

Americans watch Cricket 

Indian play Baseball 

Indian play Cricket 

Indian watch Baseball 

Indian watch Cricket 



# Task 2

In [17]:
import numpy as np
x= np.arange(5)
print(x)
def vm(arr,n):
    op= np.column_stack(x**(n-i-1) for i in range(n))
    return op

print(vm(x,5))

[0 1 2 3 4]
[[  0   0   0   0   1]
 [  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]]
